### ISSUE TITLE
vc4-kms-v3d-pi4 overlay error

### ISSUE THREAD

**Issue by kicker0429** [moonman/MyPKGBUILDs#1]
Can you please add dtoverlay=vc4-kms-v3d-pi4 to your config.txt and let me know if you get the /dev/dri/card0 device?  I tried kernels 5.6.2 and 5.4.29 by compiling with your PKGBUILD and I receive the following error messages:

Apr 03 05:28:23 RASPI4 kernel: [drm:vc5_hdmi_init_resources [vc4]] *ERROR* Failed to get HDMI state machine clock
Apr 03 05:28:23 RASPI4 kernel: vc4-drm gpu: failed to bind fef00700.hdmi (ops vc4_hdmi_ops [vc4]): -517
Apr 03 05:28:23 RASPI4 kernel: vc4-drm gpu: master bind failed: -517

**Comment by moonman** [comment]
My RPi is running headless. I'll take a look once I have time.

**Comment by Titaniumtown** [comment]
@kicker0429 I added it to mine: https://github.com/Titaniumtown/raspi4_pkgbuilds
You just have to uncomment it.
