### ISSUE TITLE
Misc distribution questions/suggestions

### ISSUE THREAD

**Issue by Titaniumtown** [moonman/MyPKGBUILDs#2]
So, on your website: (https://olegtown.pw) we can download the compiled kernel, and install it manually. But why don't you create a repository? So one could just add it to their pacman.conf, it would be so much easier than checking your website for a new update.

Another thing, these pkgbuilds, in my opinion, should be added to the aur. Are you planning on doing so?

Just some minor things, but I thank you so much for compiling packages and keeping them up to date.

**Comment by Titaniumtown** [comment]
I can even look into hosting a arch linux repository, and have the kernel build every few days. If you'll be interested in that.

**Comment by moonman** [comment]
I didn't really have time to look into creating a repo. This whole thing was created for myself and a couple of other people, and I didn't think there would be so much demand for it. I do update this once in a while when I have time, but it is not updated regularly at all. I may do it every week and then stop for a month or 2. But yeah, by all means, if you want to create a repo yourself - go for it.

**Comment by Titaniumtown** [comment]
Since you don't update it that frequently, why not make a script that checks for updates, updates the pkgbuilds, and uploads a compiled package to your website?

**Comment by moonman** [comment]
Because it needs to be tested before I upload it.

**Comment by Titaniumtown** [comment]
I'm currently working on setting up a repo :)

**Comment by Titaniumtown** [comment]
I made a repo:

[raspi_aarch64]
Server = http://107.145.175.222:8000/my_repo/aarch64/

**Comment by Titaniumtown** [comment]
@moonman did you test it? does it work?

**Comment by moonman** [comment]
It works. You need to add 
```SigLevel = Optional``` below "Server" line
Since packages are not signed.

Feel free to post it on the forum etc :)
