### ISSUE TITLE
Temperature readout doesn't work

### ISSUE THREAD

**Issue by tobbik** [moonman/MyPKGBUILDs#6]
Hi,
I upgraded to the kernel/headers/firmware combo from beginning of June (5.4.42) and get the following:
`[alarm@pi64-node1 ~]$ cat /sys/class/thermal/thermal_zone0/temp 
cat: /sys/class/thermal/thermal_zone0/temp: Invalid argument`

A downgrade to 5.4.40 fixes that

**Comment by Titaniumtown** [comment]
I have no issues, it outputs the temp for me. I compile my kernel based off of the pkgbuilds provided in this repo, with some modifications. https://github.com/Titaniumtown/raspi4_pkgbuilds

**Comment by tobbik** [comment]
Oh sorry, I forgot to mention I used the precompiled packages from here
https://olegtown.pw/Public/ArchLinuxArm/RPi4/ which I understand are built
from the PKGBUILDs in the git repository. Sorry if I got that wrong.

Tobias

**Comment by Titaniumtown** [comment]
(Not to plug my own repo)
test out my repo running on my raspberry pi 4, install packages linux-raspberrypi4-5.4.y and linux-raspberrypi4-5.4.y-headers:

[raspi_aarch64]
SigLevel = Optional
Server = http://107.145.175.222:8000/my_repo/aarch64/

**Comment by Titaniumtown** [comment]
It might be something to do with the config this repo is using, I use the official one.

**Comment by tobbik** [comment]
Hi Simon,

I wasn't very specific. I'm using the 5.4.x series. The packages I was
talking about are:
These work:
https://olegtown.pw/Public/ArchLinuxArm/RPi4/kernel/linux-raspberrypi4-5.4.40-1-aarch64.pkg.tar.xz
https://olegtown.pw/Public/ArchLinuxArm/RPi4/kernel/linux-raspberrypi4-headers-5.4.40-1-aarch64.pkg.tar.xz
and these gave me the reading error:
https://olegtown.pw/Public/ArchLinuxArm/RPi4/kernel/linux-raspberrypi4-5.4.42-1-aarch64.pkg.tar.xz
https://olegtown.pw/Public/ArchLinuxArm/RPi4/kernel/linux-raspberrypi4-headers-5.4.42-1-aarch64.pkg.tar.xz

I don't know which PKGBUIILDs they were made from.  I assumed they are
linked to your repo but I may have been wrong. Sorry for the confusion.

Tobias

**Comment by Titaniumtown** [comment]
No, I don't maintain this repo, nor the website. I just have a fork of the pkgbuilds. I just was trying to remove variables, it could be how @moonman has setup the kernel compilation config files.

**Comment by Titaniumtown** [comment]
Just trying to isolate the issue.

**Comment by Titaniumtown** [comment]
How every, I maintain my own repo that I linked above, with packages built from a foked version of the pkgbuilds here. The key difference is that I use the official config.

**Comment by moonman** [comment]
> 
> 
> Hi,
> I upgraded to the kernel/headers/firmware combo from beginning of June (5.4.42) and get the following:
> `[alarm@pi64-node1 ~]$ cat /sys/class/thermal/thermal_zone0/temp cat: /sys/class/thermal/thermal_zone0/temp: Invalid argument`
> 
> A downgrade to 5.4.40 fixes that

I'm looking into it. Something is missing from the config.


> 
> 
> How every, I maintain my own repo that I linked above, with packages built from a foked version of the pkgbuilds here. The key difference is that I use the official config.

Official defconfig is missing a ton of options. I suppose it's good enough for most people, though.

**Comment by moonman** [comment]
It should be fixed now in 5.4.44
