### ISSUE TITLE
Explanations of the kernel config for linux-raspberrypi4 on aarch64

### ISSUE THREAD

**Issue by petronny** [moonman/MyPKGBUILDs#8]
Hi,
I'm building the aarch64 version of linux-raspberrypi4.
But I don't know how do you generate the `config8` file.

Could you give me some explanations?

**Comment by moonman** [comment]
There's no magic behind it. Just use bcm2711_defconfig and then enable features that you need. I try to enable everything that can be useful + adjust certain things I know work better on other platforms, all manually. But the config doesn't need to be readjusted for a long time, usually so it 's not a big deal.

**Comment by petronny** [comment]
Why `bcm2711_defconfig` not `bcmrpi3_defconfig`?

Also I think there is a way to do this not that manually, by editing the config in `build()`:
```
build() {
  cd "${srcdir}/${_srcname}"

  make bcmrpi3_defconfig # or bcm2711_defconfig
  echo 'CONFIG_COMPAT=y' >> .config # adjust features

  [[ $CARCH == "armv7h" ]] &&  make ${MAKEFLAGS} zImage modules dtbs
  [[ $CARCH == "aarch64" ]] &&  make ${MAKEFLAGS} Image modules dtbs
}
```

Could you list the features that you adjust based on `bcm2711_defconfig` ?

**Comment by moonman** [comment]
https://www.raspberrypi.org/documentation/linux/kernel/building.md

You should never edit kernel configuration by hand like that as you are not accounting for dependencies + options change even in the same branch so scripting this will actually end being more work.

**Comment by petronny** [comment]
I see.
But I wish there could be a document that details your adjustments.

Also are the packages in olegtown.pw built in the same way as the packages in official archlinuxarm?
If so I will believe that they are well packaged so I can just use them.

**Comment by moonman** [comment]
Just diff defconfig and config8.

My packages are not signed, however I do have https setup so they are safe to download. The server is my home machine and it's routed through cloudflare.

**Comment by petronny** [comment]
Are they built in clean chroot?

**Comment by moonman** [comment]
There are no external dependencies  for a linux kernel, so it doesn't matter if it's built in a clean chroot or not.
